name: Dev Deployment

on:
  push:
    branches: [ "dev" ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Unzip build zip on EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ${{ secrets.EC2_INSTANCE_USERNAME }}
        key: ${{ secrets.EC2_INSTANCE_KEY }}
        script: |
          cd /var/www/dev/backend/main
          git pull origin dev
          git checkout dev
